-- =========================================================
-- E-COMMERCE DATA ANALYSIS PROJECT
-- =========================================================
-- Author: Shambhavi Singh
-- Description: SQL-based business analysis on e-commerce dataset
-- Database: MySQL
-- =========================================================


-- =========================================================
--  SECTION 1: OVERALL BUSINESS METRICS
-- =========================================================

-- 1. Total Revenue
-- What is the total revenue generated?
SELECT ROUND(SUM(corrected_total_price), 2) AS total_revenue
FROM order_items;

-- ==========================================================
-- Insights
-- The total revenue generated by the platform is approximately ₹74.7M, indicating a strong overall business scale. 
-- This provides a baseline to measure performance over time and compare with future periods.
-- ===========================================================

-- 2. Total Orders
-- How many total orders were placed?
SELECT COUNT(*) AS total_orders
FROM orders;

-- 3. Total Customers
-- How many unique customers do we have?
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customers;

-- 4. Average Order Value (AOV)
-- What is the average value per order?
SELECT 
    ROUND(SUM(oi.corrected_total_price) / COUNT(DISTINCT oi.order_id), 2) AS avg_order_value
FROM order_items oi;

-- ========================================================
-- Insight
-- The average order value is ₹14.9K, showing that customers generally place mid-to-high value orders. 
-- Increasing AOV through bundling or upselling could further improve revenue efficiency.
-- ========================================================

-- =========================================================
--  SECTION 2: CUSTOMER ANALYSIS
-- =========================================================

-- 5. Top 5 Customers by Spending
-- Who are the highest spending customers?
SELECT 
    o.customer_id,
    ROUND(SUM(oi.corrected_total_price), 2) AS total_spent
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY total_spent DESC
LIMIT 5;

-- =========================================================
-- Insight
-- A small group of customers contributes significantly to revenue, with CUST550 being the highest spender at ₹255K. 
-- This indicates strong customer concentration, where retaining top customers is critical for revenue stability.
-- =========================================================

-- 6. Customers Distribution by City
-- Which cities have the most customers?
SELECT 
    city,
    COUNT(*) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;

-- 7. Repeat Customers
-- Which customers placed more than one order?
SELECT 
    customer_id,
    COUNT(order_id) AS order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) > 1
ORDER BY order_count DESC;

-- ========================================================
-- Insight
-- Certain customers place significantly more repeat orders, with CUST111 leading at 17 orders. 
-- This indicates strong customer loyalty, which can be leveraged through retention strategies like rewards or memberships.
-- =========================================================
--  SECTION 3: PRODUCT ANALYSIS
-- =========================================================

-- 8. Top 5 Selling Products
-- Which products are sold the most?
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 5;

-- 9. Revenue by Product Category
-- Which category generates the most revenue?
SELECT 
    p.category,
    SUM(oi.corrected_total_price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;
-- ========================================================
-- Insight
-- Revenue is fairly balanced across categories, with Sports and Electronics leading. 
-- This shows diversified demand across product categories, reducing dependency on a single segment.
-- =========================================================

-- 10. Most Profitable Products
-- Which products generate the highest profit?
SELECT 
    p.product_name,
    ROUND(SUM(oi.corrected_total_price - (p.cost_price * oi.quantity)), 2) AS profit
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY profit DESC
LIMIT 5;

-- =========================================================
--  SECTION 4: ORDER ANALYSIS
-- =========================================================

-- 11. Orders by Status
-- What is the distribution of order statuses?
SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;
-- ========================================================
-- Insight
-- Delivered orders are slightly higher than returned and cancelled orders, but return/cancellation rates are still significant. 
-- This may indicate product quality or delivery experience issues that need attention.
-- =========================================================

-- 12. Monthly Revenue Trend
-- How does revenue change over time?
SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(oi.corrected_total_price) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;
-- ========================================================
-- Insight
-- Revenue shows a generally stable trend from June 2025 to April 2026, staying around ₹5.9M–₹6.6M per month after an initial rise. 
-- A significant drop in May 2026 (₹3.1M) breaks the pattern and may indicate incomplete data or reduced sales activity.
-- =========================================================

-- 13. Top 5 Cities by Revenue
-- Which cities generate the most revenue?
SELECT 
    c.city,
    SUM(oi.corrected_total_price) AS revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY revenue DESC
LIMIT 5;


-- =========================================================
--  SECTION 5: PAYMENT ANALYSIS
-- =========================================================

-- 14. Payment Method Distribution
-- Which payment methods are most used?
SELECT 
    payment_method,
    COUNT(*) AS total_orders
FROM payments
GROUP BY payment_method;

-- 15. Revenue by Payment Method
-- Which payment method generates most revenue?
SELECT 
    payment_method,
    SUM(payment_amount) AS total_revenue
FROM payments
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- =========================================================
--  SECTION 6: DISCOUNT & SALES IMPACT
-- =========================================================

-- 16. Discount Impact on Sales
-- Do discounts affect sales volume and revenue?
SELECT 
    CASE 
        WHEN discount = 0 THEN 'No Discount'
        ELSE 'Discount Applied'
    END AS discount_type,
    COUNT(*) AS total_orders,
    SUM(corrected_total_price) AS revenue
FROM order_items
GROUP BY discount_type;
-- ========================================================
-- Insight
-- A majority of revenue comes from orders with discounts applied. 
-- Discounted orders contribute approximately ₹49.97M, compared to ₹24.75M from non-discounted orders.
-- =========================================================

-- =========================================================
--  SECTION 7: ADVANCED ANALYSIS (WINDOW FUNCTIONS & FUNNEL)
-- =========================================================

-- 17. Customer Ranking by Revenue
-- Who are the top customers ranked by total spending?
SELECT 
    o.customer_id,
    ROUND(SUM(oi.corrected_total_price), 2) AS total_spent,
    RANK() OVER (ORDER BY SUM(oi.corrected_total_price) DESC) AS customer_rank
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.customer_id;

-- 18. Running Monthly Revenue
-- What is the cumulative revenue growth over time?
SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(oi.corrected_total_price) AS monthly_revenue,
    SUM(SUM(oi.corrected_total_price)) OVER (ORDER BY DATE_FORMAT(o.order_date, '%Y-%m')) AS cumulative_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;

-- 19. Order Status Funnel
-- What percentage of orders fall into each status?
SELECT 
    order_status,
    COUNT(*) AS total_orders,
    ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS percentage
FROM orders
GROUP BY order_status;

-- 20. Customer Lifetime Value (CLV)
-- What is total revenue per customer?
SELECT 
    o.customer_id,
    SUM(oi.corrected_total_price) AS lifetime_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY lifetime_value DESC;

-- 21. Order Frequency per Customer
-- How frequently do customers order?
SELECT 
    customer_id,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;

-- =========================================================
--  FINAL INSIGHTS SUMMARY
-- =========================================================

-- 1. The business generates strong total revenue (₹74.7M) with a healthy average order value (₹14.9K)
-- 2. Revenue remains stable monthly (₹5.9M–₹6.6M), showing consistent business performance.
-- 3. Top customers contribute a significant share of revenue, indicating dependence on high-value buyers.
-- 4. Sports and Electronics are the highest revenue-generating categories, showing strong demand concentration.
-- 5. Discounts drive most sales, but high reliance on them may impact overall profit margins.

-- =========================================================
-- END OF FILE
-- =========================================================